# Generated by Django 4.1.1 on 2022-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Agent', 'Agent'), ('Manager', 'Manager')], default='Customer', max_length=15)),
            ],
        ),
    ]
