# Generated by Django 4.1.1 on 2022-10-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete'), ('Archived', 'Archived')], default='Open', max_length=15),
        ),
    ]
