# Generated by Django 4.1.1 on 2022-10-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Agent', 'Agent'), ('Manager', 'Manager')], default='Customer', max_length=15),
        ),
    ]
