# Generated by Django 4.1.1 on 2022-10-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='role',
        ),
    ]
